In [12]:
import numpy as np
import pandas as pd

In [2]:
# creating arrays
np.zeros(5)
np.ones(10)
np.full(10, 2.5)
arr = np.array([2, 3, 5, 7])

In [22]:
arr[2] = 10
arr

array([ 2,  3, 10,  7])

In [23]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(0, 1, 11) # init range val, upper range val, size

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [25]:
# Multi-dimensional array
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr_2d[0, 1] = 10
arr_2d[2] = [20, 20, 20]
arr_2d[:, 1] = [10, 20, 30]
arr_2d

array([[ 1, 10,  3],
       [ 4, 20,  6],
       [20, 30, 20]])

In [39]:
# randomly generated array
np.random.seed(42) # fix the random version
np.random.randn(5, 2) # like allow negative value ?
np.random.randint(low=0, high=100, size=(5,2))
np.random.rand(5, 2)

array([[0.61185289, 0.13949386],
       [0.29214465, 0.36636184],
       [0.45606998, 0.78517596],
       [0.19967378, 0.51423444],
       [0.59241457, 0.04645041]])

In [49]:
# Element-wise operations
arr_e = np.arange(5) # [0, 1, 2, 3, 4]
arr_b = (arr_e * 2 + 1) ** 2 / 10
arr_e + arr_b # array([ 0.1,  1.9,  4.5,  7.9, 12.1])

# comparision
arr_e >= 3 # array([False, False, False,  True,  True])
arr_e > arr_b
arr_b[arr_e > arr_b] # array([0.9])

array([0.9])

In [51]:
arr_b.std() # np.float64(2.9065443399335917)
arr_e.min() # np.int64(0)

np.int64(0)

In [53]:
# vector operations
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])
u + v # array([3, 4, 5, 8])
u * v # array([ 2,  0,  0, 12])

array([ 2,  0,  0, 12])

In [58]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    result = 0.0
    n = u.shape[0]
    for i in range (n):
        result = result + u[i] * v[i]
    return result
vector_vector_multiplication(u, v)
u.dot(v)

np.int64(14)

In [5]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

def matrix_matrix_multiplication(u, v):
    assert u.shape[1] == v.shape[0]
    n = u.shape[0] # rows
    m = v.shape[1] # cols
    newmat = np.zeros((n, m))
    for i in range(m):
        # for j in range(n):
        vi = v[:, i]
        val = u.dot(vi) # vector multiplication
        newmat[:, i] = val
    return newmat

matrix_matrix_multiplication(U, V)
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [11]:
I = np.eye(3) # identity matrix 
Vs = V[[0, 1, 2]]
np.linalg.inv(Vs) # inverse

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])